# author : 이승민
# docker-compose.yml

services:
  web:
    build: .
    container_name: IdeaConcert
    command:
      - bash
      - -c
      - |
        python manage.py collectstatic --noinput
        gunicorn IdeaConcert.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/server/IdeaConcert/
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web